### ISSUE TITLE
Congratz, this seems very useful!

### ISSUE THREAD

**Issue by hakunin** [ankane/notable_web#1]
Two ideas:
- how a bout a screenshot?
- I'll definitely want to embed this into active admin if I use i

**Comment by ankane** [comment]
Thanks Michal.
1. I plan to add a screenshot, demo, and much better UI soon
2. I haven't used active admin much - is it easy to embed engines? (another option would be link to it)

**Comment by hakunin** [comment]
I think you'd have to build the engine with active admin in mind from the start. It could be easy to build it like that, but I'd say too time consuming to port when you have something bigger.

I'll check notable_web out when I am going to add analytics to my project and see how it could be embedded.

Meanwhile a screenshot would be nice to whet my appetite :)

**Comment by ankane** [comment]
Cleaning up stale issues. Never did take that screenshot...
