### ISSUE TITLE
Kaminari and Will_paginate Error

### ISSUE THREAD

**Issue by taiwoayanleye** [ankane/notable_web#3]
**"notable_web" gem works without pagination gems but raises error when otherwise**
I had the "notable_web" gem work on my app before, but recently I added the "will_paginate" gem along with "kaminari" gem that I had before.

Then it raises this error when I visit the "domain.com/notable" from my app on development mode:
**undefined method `per' for #Notable::Request::ActiveRecord_Relation:0x007fee49cbc250**

when I took off the "will_paginate" gem, here was the error I got:
**undefined method `page' for #Notable::Request::ActiveRecord_Relation:0x007fee49cbc250**

Kindly advise :)

**Comment by Andrianka** [comment]
I also have this problem. :(

**Comment by benortiz** [comment]
@onlyyouandty and @Andrianka I found this that worked perfectly for me in solving this problem: http://tech-brains.blogspot.in/2012/11/kaminari-willpaginate-incompatibility.html

```
if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        def per(value = nil) per_page(value) end
        def total_count() count end
      end
    end
    module CollectionMethods
      alias_method :num_pages, :total_pages
    end
  end
end
```

**Comment by ACPK** [comment]
@ankane Same issue. I get a "attempting to generate a URL from non-sanitized request parameters" error for this gem when Kaminari is installed.

**Comment by ACPK** [comment]
@onlyyouandty - Any advice? :)

**Comment by ankane** [comment]
Hey all, sorry for the delayed response. See the will_paginate section of the readme for how to fix conflicts.
