### ISSUE TITLE
Upgrade for Rails 5+

### ISSUE THREAD

**Issue by afstanton** [ankane/notable_web#5]
undefined method `map' for <ActionController::Parameters {} permitted: true>:ActionController::Parameters

Cause by line 8 of indexnotable_web (0.0.1) app/controllers/notable_web/home_controller.rb

Thanks!

**Comment by ankane** [comment]
Hey @afstanton, thanks for reporting 👍  Fixed on master.

**Comment by afstanton** [comment]
Awesome! Thanks!
