### ISSUE TITLE
Error with Rails 5.1.4 (not sure about earlier versions) in master

### ISSUE THREAD

**Issue by afstanton** [ankane/notable_web#6]
Error in actionpack (5.1.4) lib/action_controller/metal/strong_parameters.rb, line 265
to_h fails "permitted?" and raises UnfilteredParameters

**Comment by ankane** [comment]
Hey @afstanton, what URL are you seeing that on? I'm unable to reproduce with 5.1.4.

**Comment by afstanton** [comment]
How...odd. You're right. Master is working. I'm wondering if this was an issue with something else.

Sorry about that!
