### ISSUE TITLE
Showing list of requests: Unable to convert unpermitted parameters to hash

### ISSUE THREAD

**Issue by Laykou** [ankane/notable_web#9]
```
ActionController::UnfilteredParameters at /
unable to convert unpermitted parameters to hash
```
This happens because 

```ruby
params.slice(:status, :note_type, :scope).merge(user_id: request.user_id, user_type: request.user_type)
```

in `app/views/notable_web/home/_stream.html.erb` returns unpermitted hash:

```
<ActionController::Parameters {"scope"=>"slow_requests", "user_id"=>1, "user_type"=>"User"} permitted: false>
```

![image](https://user-images.githubusercontent.com/2313005/67678136-2993d980-f986-11e9-8ba7-a1245538d4c6.png)

**Comment by ankane** [comment]
Hey @Laykou, it looks like that's an older version. Try upgrading to the latest version.

**Comment by b4k3r** [comment]
Hi @ankane,

As I see @Laykou used the latest version of your gem (0.1.1). Based on your provided fix https://github.com/ankane/notable_web/commit/e310ff831a70d266f5bb3d4f19f5a2d2d4959a34 shouldn't be used `@safe_params` variable in the 14th line in `app/views/notable_web/home/_stream.html.erb`?

**Comment by ankane** [comment]
Hey @b4k3r, thanks for pointing that out (not sure why I thought 0.1.1 was an earlier version - was maybe looking at Notable). Can you try master?

**Comment by b4k3r** [comment]
Works! Thank you for your quick action :)
